# Generated by Django 5.1.6 on 2025-02-08 22:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParType',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('fr_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('fr_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Champion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('fr_name', models.CharField(max_length=100)),
                ('key', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=100)),
                ('sprite', models.CharField(max_length=100)),
                ('lore', models.TextField()),
                ('fr_lore', models.TextField()),
                ('title', models.CharField(max_length=100)),
                ('fr_title', models.CharField(max_length=100)),
                ('par_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.partype')),
                ('tags', models.ManyToManyField(to='game.tag')),
            ],
        ),
    ]
