# Generated by Django 5.1.6 on 2025-02-07 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParType',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('fr_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('fr_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Champion',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('fr_name', models.CharField(max_length=100)),
                ('key', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=100)),
                ('sprite', models.CharField(max_length=100)),
                ('lore', models.TextField()),
                ('fr_lore', models.TextField()),
                ('par_types', models.ManyToManyField(to='game.partype')),
                ('tags', models.ManyToManyField(to='game.tag')),
            ],
        ),
    ]
