# Generated by Django 5.1.6 on 2025-02-12 00:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('jwttoken', models.CharField(editable=False, max_length=100)),
                ('last_game', models.DateTimeField(auto_now=True)),
                ('champion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='game.champion')),
            ],
        ),
    ]
