# Generated by Django 5.1.6 on 2025-02-13 21:37

import shortuuid.django_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_alter_player_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', shortuuid.django_fields.ShortUUIDField(alphabet=None, editable=False, length=22, max_length=8, prefix='', primary_key=True, serialize=False)),
                ('players', models.ManyToManyField(max_length=2, to='game.player')),
            ],
        ),
    ]
