# Generated by Django 5.1.6 on 2025-02-13 21:39

import shortuuid.django_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_party'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet=None, editable=False, length=8, max_length=8, prefix='', primary_key=True, serialize=False),
        ),
    ]
